defaultPortal: matt-practicum
portals:
  - name: matt-practicum
    portalId: 22127437
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CPOzirWyMRIOAAUAQAAAAGwAQAJYAgEYzcbGCiCYsbIVKO7pDDIUoUpDtrMTcfCvSRaIilKRUShr06I6MAAABEEAAAAAAAAAAAAAAAAAgAAAAAAABAAAAAAAAAAAPGBQAABEAABA_BgGABAgA0IUjyEJNLlgJVzk-A7iSJ9ETy8oHyNKA25hMVIAWgA
        expiresAt: '2023-10-13T01:24:32.391Z'
    personalAccessKey: >-
      CiRjM2ZmNzJjMi0yMTczLTRmZTEtYTRhMy1lMDI4YWI1Y2I3ZTMQzcbGChiYsbIVKhkABeaRgk5bX3BOuYPzexwlhOYvKCP7UxQjSgNuYTE
    sandboxAccountType: null
    parentAccountId: null
