defaultPortal: matt-practicum
portals:
  - name: matt-practicum
    portalId: 22127437
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          COPly7WrMRIOAAUAQAAAAGwAQAJYAgEYzcbGCiCYsbIVKO7pDDIUjsUMG5kHVQ2pUw9W6gtF7cQaSdw6MAAABEEAAAAAAAAAAAAAAAAAgAAAAAAABAAAAAAAAAAAPGBQAABEAABA_BgGABAgA0IUe-Hqr8nvfFaV3MCzpltUUiG7UJ1KA25hMVIAWgA
        expiresAt: '2023-09-21T07:44:55.543Z'
    personalAccessKey: >-
      CiRjM2ZmNzJjMi0yMTczLTRmZTEtYTRhMy1lMDI4YWI1Y2I3ZTMQzcbGChiYsbIVKhkABeaRgk5bX3BOuYPzexwlhOYvKCP7UxQjSgNuYTE
    sandboxAccountType: null
    parentAccountId: null
