defaultPortal: matt-practicum
portals:
  - name: matt-practicum
    portalId: 22127437
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CMrGvt2rMRIOAAUAQAAAAGwAQAJYAgEYzcbGCiCYsbIVKO7pDDIUyJjeZy0r-3ubiw8cehPWc-j_QAc6MAAABEEAAAAAAAAAAAAAAAAAgAAAAAAABAAAAAAAAAAAPGBQAABEAABA_BgGABAgA0IUexCuQGDIOAGAiuiJgCvKaikFkORKA25hMVIAWgA
        expiresAt: '2023-09-22T06:59:24.637Z'
    personalAccessKey: >-
      CiRjM2ZmNzJjMi0yMTczLTRmZTEtYTRhMy1lMDI4YWI1Y2I3ZTMQzcbGChiYsbIVKhkABeaRgk5bX3BOuYPzexwlhOYvKCP7UxQjSgNuYTE
    sandboxAccountType: null
    parentAccountId: null
